# See https://wiki.hyprland.org/Configuring/Monitors/
# List current monitors and resolutions possible: hyprctl monitors
# Format: monitor = [port], resolution, position, scale

env = GDK_SCALE,1
#monitor=,preferred,auto,auto
monitor=eDP-1, 1920x1080@60, 5120x0, 1
monitor=DP-2, 5120x1440@120, 0x0, 1


# Workspaces
# In the case of multiple screens, my laptop should 
# Laptop dedicated to 5
workspace = 9, monitor:eDP-1, layoutopt:orientation:left

workspace = 1, monitor:DP-2
workspace = 2, monitor:DP-2
workspace = 3, monitor:DP-2
workspace = 4, monitor:DP-2
workspace = 5, monitor:DP-2
workspace = 6, monitor:DP-2
workspace = 7, monitor:DP-2
workspace = 8, monitor:DP-2
