return {
  "neovim/nvim-lspconfig",
  opts = {
    servers = {
      gopls = {},
      html = {},
      pyright = {},

      -- Arduino sketches.
      --
      -- arduino-language-server can't resolve Go-to-Definition across a
      -- sketch's sibling .cpp files, so a *multi-file* sketch (like
      -- src/radiator) is better driven by clangd. But simple .ino-only
      -- sketches have no compile_commands.json and work fine with
      -- arduino-language-server, which I want to keep for them.
      --
      -- The presence of a compile_commands.json (generated by
      -- src/radiator/gen_compile_commands.py) is the switch:
      --   has DB -> clangd owns the .ino; arduino-language-server stands down
      --   no DB  -> arduino-language-server owns the .ino; clangd stands down
      -- Each server's root_dir returns nil (no attach) in the case it should
      -- defer, so exactly one attaches to any given .ino.
      clangd = {
        -- Whitelist the ESP32 cross-compiler as a query-driver so clangd asks
        -- xtensa-esp32s3-elf-gcc for its sysroot include paths (e.g.
        -- machine/endian.h); without this clangd uses host headers and can't
        -- resolve the Xtensa newlib ones. Flag-stripping lives in the sketch's
        -- .clangd; this part is per-machine, hence here not in the repo.
        cmd = {
          "clangd",
          -- glob the g* suffix: the sketch compiles via the C++ driver
          -- (xtensa-esp32s3-elf-g++), not -gcc, so it must match both.
          "--query-driver=" .. vim.fn.expand("~")
            .. "/.arduino15/packages/esp32/tools/xtensa-esp32s3-elf-gcc/*/bin/xtensa-esp32s3-elf-g*",
        },
        filetypes = { "c", "cpp", "objc", "objcpp", "cuda", "proto", "arduino" },
        -- clangd doesn't recognise the .ino extension; report the arduino
        -- filetype as C++ so the sketch parses with the C++ frontend.
        get_language_id = function(_, ftype)
          if ftype == "arduino" then
            return "cpp"
          end
          local t = { objc = "objective-c", objcpp = "objective-cpp", cuda = "cuda-cpp" }
          return t[ftype] or ftype
        end,
        root_dir = function(bufnr, on_dir)
          local fname = vim.api.nvim_buf_get_name(bufnr)
          local dir = vim.fs.dirname(fname)
          if vim.bo[bufnr].filetype == "arduino" then
            -- Only claim a .ino when its sketch has a compile DB; otherwise
            -- leave it to arduino-language-server.
            local cc = vim.fs.find("compile_commands.json", { upward = true, path = dir })[1]
            if cc then
              on_dir(vim.fs.dirname(cc))
            end
            return
          end
          -- Unchanged C/C++ behaviour (mirrors the markers in lsp/clangd.lua).
          on_dir(vim.fs.root(fname, {
            ".clangd", ".clang-tidy", ".clang-format",
            "compile_commands.json", "compile_flags.txt", "configure.ac", ".git",
          }))
        end,
      },
      arduino_language_server = {
        -- Stand down for sketches that have a compile_commands.json (clangd
        -- handles those); drive every other .ino sketch as usual.
        root_dir = function(bufnr, on_dir)
          local fname = vim.api.nvim_buf_get_name(bufnr)
          local dir = vim.fs.dirname(fname)
          if vim.fs.find("compile_commands.json", { upward = true, path = dir })[1] then
            return
          end
          on_dir(require("lspconfig.util").root_pattern("*.ino")(fname))
        end,
      },
    },
  },
}
